name: Generate Protobuf

on:
  push:
    branches: [ "main" ]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install protoc plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Generate Go code
        run: |
          mkdir -p out

          protoc \
            --go_out=out \
            --go-grpc_out=out \
            payment/payment.proto

      - name: Push to proto-generated repo
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git clone https://x-access-token:${TOKEN}@github.com/tolik-tachyon/proto-generated.git

          rm -rf proto-generated/* || true
          cp -r out/* proto-generated/

          cd proto-generated
          git add .
          git commit -m "auto generate proto" || echo "no changes"
          git push
