name: Generate Protobuf

on:
  push:
    branches: ["main"]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Add Go bin to PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Generate
        run: |
          rm -rf paymentpb
          mkdir -p paymentpb

          protoc \
            --go_out=paymentpb \
            --go-grpc_out=paymentpb \
            payment/payment.proto

      - name: Checkout generated repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/tolik-tachyon/proto-generated.git

      - name: Verify output
        run: |
          echo "=== generated files ==="
          ls -R paymentpb || (echo "NO GENERATED FILES" && exit 1)

      - name: Sync files
        run: |
          rm -rf proto-generated/paymentpb
          mkdir -p proto-generated/paymentpb
          cp -r paymentpb/* proto-generated/paymentpb/

      - name: Init Go module
        run: |
          cd proto-generated
          go mod init github.com/tolik-tachyon/proto-generated || true
          go mod tidy || true

      - name: Commit & push
        run: |
          cd proto-generated
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "auto generate proto" || echo "no changes"
          git push