name: Generate Protobuf

on:
  push:
    paths:
      - "proto-contracts/**"
      - ".github/workflows/generate.yml"

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Install Go protobuf plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Clone generated repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/tolik-tachyon/proto-generated.git out

      - name: Generate Go code
        run: |
          mkdir -p out/paymentpb
          protoc \
            --proto_path=proto-contracts/payment \
            --go_out=out/paymentpb \
            --go-grpc_out=out/paymentpb \
            proto-contracts/payment/payment.proto

      - name: Init Go module if needed
        run: |
          cd out
          if [ ! -f go.mod ]; then
            go mod init github.com/tolik-tachyon/proto-generated
          fi
          go mod tidy

      - name: Commit and push changes
        run: |
          cd out
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "update generated proto" || exit 0
          git push